= nix-gradle-javatoolchain-kotlin-no-class-roots

This demonstrates an issue with the combination of the current (see `flake.lock`)
versions of `gradle` and `jdk23` nixpkgs `github:nixos/nixpkgs/nixos-unstable`. The problem
occurs when compiling Kotlin using the `javaToolchains` feature of Gradle with `jdk23` being
made available as a JDK via `javaToolchains` in `gradle.override`.

See: https://github.com/NixOS/nixpkgs/issues/360954

To reproduce (on Linux)  use:

. `git clone git@github.com:msgilligan/nix-gradle-javatoolchain-kotlin-no-class-roots.git`
. `cd nix-gradle-javatoolchain-kotlin-no-class-roots`
. `nix develop`
. `gradle build`

You should get the following error:

```
> Task :compileKotlin FAILED
e: No class roots are found in the JDK path: /nix/store/a1k4dqs487q2xnimym388bkqg99agdsl-openjdk-23.0.1+11

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

The problem only seems to happen on Linux (not macOS, I'm using aarch64 for both) and can be worked-around
with either of the following changes:

. Comment out the following line in `build.gradle`
+ 
	//jvmToolchain(23)

. Replace `jdk23` with `temurin-bin-23` in `flake.nix`, like this:
+
	(gradle.override {
		javaToolchains = [ temurin-bin-23 ]; # Put JDK 23 in Gradle's javaToolchain configuration
	})

. Replace `javaToolchains = [ jdk23 ]` with `java =  jdk23` in `flake.nix` (see PR #1), like this:
+
	(gradle.override {
		java =  jdk23 ; # Run Gradle with  JDK 23
	})

== Updates

* Update 2025-02-25: Kotlin plugin updated to 2.1.10 and `nix flake update` were committed to `master`


